
# database
#spring.datasource.url=jdbc:mysql://localhost:3306/authentication-server
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=create

# database
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/authentication-server
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


# OAuth2 for Google

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 822170521822-im7qjg0mv94v7qo3nc29a5i9e4f4or20.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: YOUR CLIENT ID GOES HERE
            client-secret: YOUR CLIENT SECRET GOES HERE